### PR TITLE
Add file-like support for hts readers

### PR DESCRIPTION
**Pull request by nvictus**

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
Is there a Python code snippet I could use to test this?

Looks like `read_bam(open('my.bam', 'r'), region='chr1:1-1000', index=open('my.bai', 'r'))`?

Is there a tutorial for installing oxbox to use with Python bindings?  The docs at https://docs.rs/oxbow/latest/oxbow/ only seem to have Rust examples?

**Comment by nvictus** [comment]
> Looks like read_bam(open('my.bam', 'r'), region='chr1:1-1000', index=open('my.bai', 'r'))?
Yes

>Is there a Python code snippet I could use to test this?
Not yet. I've been testing in a notebook.

> Is there a tutorial for installing oxbox to use with Python bindings?
Not yet. We'll need to add a pytest suite and basic sphinx docs for pyoxbow in the next release. I'll make them issues separate from this PR.

**Review by GarrettNg — APPROVED** [review]

**Comment by pkerpedjiev** [comment]
> Not yet. I've been testing in a notebook.

Would you be willing to share that notebook? I'd love to try it out.

**Comment by nvictus** [comment]
https://gist.github.com/nvictus/6acd49d53001feed268cfe3193a017b0

**Pull request merged**
